feature: ['feature/*', 'feat/*']
bugfix: ['bugfix/*', 'bug/*', 'fix/*']
chore: ['chore/*', 'maintenance/*']
config: ['config/*', 'configuration/*']
documentation: ['docs/*', 'doc/*', 'documentation/*']
test: ['test/*', 'tests/*', 'testing/*', 'integration-tests/*']
ci: ['ci/*', 'ci-cd/*', 'cicd/*']
refactor: ['refactor/*', 'refactoring/*']
performance: ['performance/*', 'perf/*']
security: ['security/*', 'sec/*']
build: ['build/*', 'build-system/*']
dependencies: ['dependencies/*', 'deps/*', 'dependency-update/*']
release: ['release/*', 'releasing/*']
hotfix: ['hotfix/*', 'hot-fix/*']
ux: ['ux/*', 'ui/*', 'ui-ux/*']
style: ['style/*', 'styles/*', 'formatting/*', 'code-style/*']
frontend: ['frontend/*', 'front-end/*']
backend: ['backend/*', 'back-end/*']
api: ['api/*', 'api-change/*', 'api-updates/*']
infrastructure: ['infrastructure/*', 'infra/*', 'platform/*']
