addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.10.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.5.5")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.11.2")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"  % "0.13.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "2.4.0")
